[[ plugins ]]
    package = "/plugins"

[build]
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./src ./public ./plugin .nvmrc index.html netlify.toml package.json tsconfig.json vite.config.ts vitest.config.ts yarn.lock"